package hola;
// Generated 10/03/2016 01:39:20 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Apellido generated by hbm2java
 */
public class Apellido  implements java.io.Serializable {


     private int id;
     private Integer apellidoP;
     private Serializable apellidoM;

    public Apellido() {
    }

	
    public Apellido(int id) {
        this.id = id;
    }
    public Apellido(int id, Integer apellidoP, Serializable apellidoM) {
       this.id = id;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(Integer apellidoP) {
        this.apellidoP = apellidoP;
    }
    public Serializable getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(Serializable apellidoM) {
        this.apellidoM = apellidoM;
    }




}


